# Simple workflow for deploying static content to GitHub Pages
name: Build, Test, npm Publish, and Deploy

on: [push, pull_request]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  # Test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
